#!/usr/bin/env python3
"""Generate and build a representative project with the public CLI.

The script intentionally uses only the Python standard library so that the
same verification path works on Windows, Linux and macOS. It expects the
public CLI contract documented in README.md: options are passed to the CLI and
the ZIP is written to stdout. A compatible downstream CLI can override the
argument list with ICARUS_CLI_ARGS_JSON, a JSON array of option strings.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile


DEFAULT_ARGS = [
    "--artifact",
    "demo-service",
    "--group",
    "com.example.demo",
    "--package",
    "com.example.demo",
    "--port",
    "8080",
    "--description",
    "Generated sample",
]


class VerificationError(RuntimeError):
    """A safe, user-actionable verification failure."""


def run(command: list[str], cwd: Path) -> None:
    print(f"$ {' '.join(command)}", flush=True)
    completed = subprocess.run(command, cwd=cwd, check=False)
    if completed.returncode != 0:
        raise VerificationError(
            f"Command exited with status {completed.returncode}: {command[0]}"
        )


def executable_command(path: Path) -> list[str]:
    """Return a subprocess command that works for Unix and Windows wrappers."""

    if os.name == "nt" and path.suffix.lower() in {".cmd", ".bat"}:
        return ["cmd", "/d", "/c", str(path)]
    if os.name != "nt" and path.name == "mvnw" and not os.access(path, os.X_OK):
        return ["sh", str(path)]
    return [str(path)]


def find_maven(root: Path) -> list[str]:
    wrapper = root / ("mvnw.cmd" if os.name == "nt" else "mvnw")
    if wrapper.is_file():
        return executable_command(wrapper)

    for candidate in ("mvn", "mvn.cmd"):
        resolved = shutil.which(candidate)
        if resolved:
            return executable_command(Path(resolved))
    raise VerificationError(
        "Maven was not found. Install Maven 3.9+ or add mvnw/mvnw.cmd to the project."
    )


def find_cli_jar(root: Path) -> Path:
    target = root / "icarus-scaffold-cli" / "target"
    if not target.is_dir():
        raise VerificationError(
            "icarus-scaffold-cli/target is missing; build the Maven reactor before generating a sample."
        )

    candidates = []
    for jar in target.glob("*.jar"):
        name = jar.name
        if any(
            marker in name
            for marker in ("-sources.jar", "-javadoc.jar", "-tests.jar")
        ) or name.startswith("original-"):
            continue
        candidates.append(jar)
    if not candidates:
        raise VerificationError("No runnable CLI jar was found in icarus-scaffold-cli/target.")
    executable = [jar for jar in candidates if jar.stem.endswith("-all")]
    if executable:
        return max(executable, key=lambda path: path.stat().st_mtime_ns)
    raise VerificationError("No executable CLI *-all.jar was found in icarus-scaffold-cli/target.")


def prepare_output_dir(root: Path, requested: Path | None) -> Path:
    if requested is None:
        output_dir = Path(tempfile.mkdtemp(prefix="icarus-scaffold-sample-"))
        (output_dir / ".generated-by-icarus-scaffold").write_text(
            "Generated by scripts/generate-sample.py; safe to remove.\n",
            encoding="utf-8",
        )
        return output_dir

    output_dir = requested if requested.is_absolute() else root / requested
    output_dir = output_dir.resolve()
    root_resolved = root.resolve()
    ci_entry = root_resolved / ".ci"
    if ci_entry.is_symlink():
        raise VerificationError("The repository .ci directory must not be a symbolic link.")
    ci_root = ci_entry.resolve()
    try:
        relative_to_ci = output_dir.relative_to(ci_root)
    except ValueError as exc:
        raise VerificationError("--output-dir must be a child of the repository .ci directory.") from exc
    if not relative_to_ci.parts:
        raise VerificationError("--output-dir must not be the .ci directory itself.")

    marker = output_dir / ".generated-by-icarus-scaffold"
    if output_dir.exists():
        if not marker.is_file():
            raise VerificationError(
                f"Refusing to replace existing unmarked directory: {output_dir}"
            )
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=False)
    (output_dir / ".generated-by-icarus-scaffold").write_text(
        "Generated by scripts/generate-sample.py; safe to remove.\n",
        encoding="utf-8",
    )
    return output_dir


def cli_args() -> list[str]:
    raw = os.environ.get("ICARUS_CLI_ARGS_JSON")
    if not raw:
        values = DEFAULT_ARGS.copy()
    else:
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise VerificationError("ICARUS_CLI_ARGS_JSON must be a JSON array.") from exc
        if not isinstance(parsed, list) or not all(isinstance(item, str) for item in parsed):
            raise VerificationError("ICARUS_CLI_ARGS_JSON must contain only strings.")
        values = parsed

    if any("{output}" in value for value in values):
        raise VerificationError(
            "ICARUS_CLI_ARGS_JSON must not pass an output path; the public CLI writes the ZIP to stdout."
        )
    return values


def run_cli(
    java: str,
    cli_jar: Path,
    arguments: list[str],
    output_zip: Path,
    cwd: Path,
) -> None:
    command = [java, "-jar", str(cli_jar), *arguments]
    print(f"$ {' '.join(command)} > {output_zip}", flush=True)
    with output_zip.open("wb") as output:
        completed = subprocess.run(command, cwd=cwd, stdout=output, check=False)
    if completed.returncode != 0:
        output_zip.unlink(missing_ok=True)
        raise VerificationError(
            f"CLI exited with status {completed.returncode}; see stderr for details."
        )


def validate_zip(zip_path: Path, output_dir: Path) -> Path:
    if not zip_path.is_file() or zip_path.stat().st_size == 0:
        raise VerificationError(f"CLI did not create a non-empty ZIP: {zip_path}")
    if zip_path.stat().st_size > 2 * 1024 * 1024:
        raise VerificationError("Generated ZIP exceeds the 2 MiB compressed-size limit.")

    extracted = output_dir / "extracted"
    extracted.mkdir()
    seen: set[str] = set()
    max_entries = 200
    max_file_bytes = 512 * 1024
    max_total_bytes = 4 * 1024 * 1024
    total_bytes = 0
    with zipfile.ZipFile(zip_path) as archive:
        if len(archive.infolist()) > max_entries:
            raise VerificationError("Generated ZIP contains too many entries.")
        for info in archive.infolist():
            name = info.filename.replace("\\", "/")
            path = PurePosixPath(name)
            if (
                not name
                or name.startswith("/")
                or re.match(r"^[A-Za-z]:", name)
                or path.is_absolute()
                or ".." in path.parts
            ):
                raise VerificationError(f"Unsafe ZIP entry: {info.filename!r}")
            if name in seen:
                raise VerificationError(f"Duplicate ZIP entry: {info.filename!r}")
            if info.file_size > max_file_bytes:
                raise VerificationError(f"Generated ZIP entry is too large: {info.filename!r}")
            total_bytes += info.file_size
            if total_bytes > max_total_bytes:
                raise VerificationError("Generated ZIP expands beyond the allowed size.")
            seen.add(name)
        archive.extractall(extracted)

    pom_files = sorted(
        (path for path in extracted.rglob("pom.xml") if path.is_file()),
        key=lambda path: (len(path.relative_to(extracted).parts), str(path)),
    )
    if not pom_files:
        raise VerificationError("Generated ZIP does not contain a pom.xml.")
    return pom_files[0].parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Keep the ZIP and extracted sample under this repository-relative directory.",
    )
    return parser.parse_args()


def display_path(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def main() -> int:
    options = parse_args()
    root = options.root.resolve()
    if not (root / "pom.xml").is_file():
        raise VerificationError(f"Repository root does not contain pom.xml: {root}")

    output_dir = prepare_output_dir(root, options.output_dir)
    remove_after_check = options.output_dir is None
    try:
        zip_path = output_dir / "demo-service.zip"
        maven = find_maven(root)
        cli_jar = find_cli_jar(root)
        java = shutil.which("java")
        if not java:
            raise VerificationError("Java was not found on PATH.")

        run_cli(java, cli_jar, cli_args(), zip_path, root)
        project_root = validate_zip(zip_path, output_dir)

        try:
            project_maven = find_maven(project_root)
        except VerificationError:
            project_maven = maven
        run(project_maven + ["-B", "-ntp", "-Dstyle.color=never", "test"], project_root)
        (output_dir / "sample-build.txt").write_text(
            f"CLI jar: {cli_jar.relative_to(root)}\n"
            f"Generated ZIP: {display_path(zip_path, root)}\n"
            f"Generated project: {project_root.relative_to(output_dir)}\n"
            "Result: Maven test completed successfully\n",
            encoding="utf-8",
        )
        if remove_after_check:
            print("Generated and tested a temporary sample; verification artifacts will be removed.")
        else:
            print(f"Generated and tested sample: {zip_path}")
    finally:
        if remove_after_check and output_dir.exists():
            shutil.rmtree(output_dir)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except VerificationError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
